sonar.projectKey=vitacase-plataforma-saude
sonar.projectName=VitaCase - Plataforma de Gestão em Saúde
sonar.projectVersion=1.0

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.cy.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.EXEMPLO.*,**/prisma/migrations/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.typescript.tsconfigPath=backend/tsconfig.json

sonar.sourceEncoding=UTF-8
